# Pandas Notebook

## Theory

**Pandas** is a Python library for data analysis and manipulation.

### Main Data Structures
- **Series**: One-dimensional labeled array.

| Index | Value |
|------:|------:|
|0|10|
|1|20|
|2|30|

- **DataFrame**: Two-dimensional table.

| Name | Age | City |
|------|----:|------|
| Ram |20|Kathmandu|
| Hari |22|Pokhara|
| Sita |21|Butwal|

## Import Pandas

In [2]:
import pandas as pd

## Create Series

In [3]:
s = pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

## Create DataFrame

In [4]:
data={'Name':['Ram','Hari','Sita'],'Age':[20,22,21],'City':['Kathmandu','Pokhara','Butwal']}
df=pd.DataFrame(data)
df

   Name  Age       City
0   Ram   20  Kathmandu
1  Hari   22    Pokhara
2  Sita   21     Butwal

## Head

In [5]:
df.head()

   Name  Age       City
0   Ram   20  Kathmandu
1  Hari   22    Pokhara
2  Sita   21     Butwal

## Tail

In [6]:
df.tail()

   Name  Age       City
0   Ram   20  Kathmandu
1  Hari   22    Pokhara
2  Sita   21     Butwal

## Columns

In [7]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

## Shape

In [8]:
df.shape

(3, 3)

## Data Types

In [9]:
df.dtypes

Name    object
Age      int64
City    object
dtype: object

## Info

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

## Describe

In [11]:
df.describe()

        Age
count   3.0
mean   21.0
std     1.0
min    20.0
25%    20.5
50%    21.0
75%    21.5
max    22.0

## Select Column

In [12]:
df['Name']

0     Ram
1    Hari
2    Sita
Name: Name, dtype: object

## Multiple Columns

In [13]:
df[['Name','Age']]

   Name  Age
0   Ram   20
1  Hari   22
2  Sita   21

## loc

In [ ]:
df.loc[1]

## iloc

In [14]:
df.iloc[2]

Name      Sita
Age         21
City    Butwal
Name: 2, dtype: object

## Filter

In [15]:
df[df['Age']>20]

   Name  Age     City
1  Hari   22  Pokhara
2  Sita   21   Butwal

## Add Column

In [16]:
df['Marks']=[80,90,85]
df

   Name  Age       City  Marks
0   Ram   20  Kathmandu     80
1  Hari   22    Pokhara     90
2  Sita   21     Butwal     85

## Update

In [17]:
df.loc[0,'Marks']=95
df

   Name  Age       City  Marks
0   Ram   20  Kathmandu     95
1  Hari   22    Pokhara     90
2  Sita   21     Butwal     85

## Drop Column

In [18]:
df=df.drop('Marks',axis=1)
df

   Name  Age       City
0   Ram   20  Kathmandu
1  Hari   22    Pokhara
2  Sita   21     Butwal

## Sort

In [19]:
df.sort_values(by='Age')

   Name  Age       City
0   Ram   20  Kathmandu
2  Sita   21     Butwal
1  Hari   22    Pokhara

## Read CSV

In [20]:
# df = pd.read_csv('students.csv')

## Save CSV

In [21]:
# df.to_csv('new_students.csv', index=False)

## Missing Values

In [22]:
df.isnull().sum()

Name    0
Age     0
City    0
dtype: int64

## Fill Missing

In [23]:
df.fillna(0)

   Name  Age       City
0   Ram   20  Kathmandu
1  Hari   22    Pokhara
2  Sita   21     Butwal

## Max

In [24]:
df['Age'].max()

np.int64(22)

## Min

In [25]:
df['Age'].min()

np.int64(20)

## Mean

In [26]:
df['Age'].mean()

np.float64(21.0)

## Sum

In [27]:
df['Age'].sum()

np.int64(63)

## Unique

In [28]:
df['City'].unique()

array(['Kathmandu', 'Pokhara', 'Butwal'], dtype=object)

## Value Counts

In [29]:
df['City'].value_counts()

City
Kathmandu    1
Pokhara      1
Butwal       1
Name: count, dtype: int64

## Cheat Sheet

| Function | Purpose |
|---|---|
| pd.Series() | Create Series |
| pd.DataFrame() | Create DataFrame |
| head() | First rows |
| tail() | Last rows |
| info() | Dataset info |
| describe() | Statistics |
| loc[] | Label indexing |
| iloc[] | Position indexing |
| read_csv() | Read CSV |
| to_csv() | Save CSV |
| isnull() | Check missing |
| fillna() | Fill missing |
| sort_values() | Sort data |